version: '2'
services:
  nginx:
    container_name: ${PROJECT}_nginx
    build:
      context: ./docker/nginx
      args:
        HOST_UID: ${HOST_UID}
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    container_name: ${PROJECT}_php
    build:
      context: ./docker/php
      args:
        HOST_UID: ${HOST_UID}
        XDEBUG_IP: ${XDEBUG_IP}
        XDEBUG_PORT: $XDEBUG_PORT
    volumes:
      - ./:/var/www/html

  mysql:
    container_name: ${PROJECT}_mysql
    build:
        context: ./docker/mysql
        args:
            HOST_UID: ${HOST_UID}
    volumes:
        - ./docker/runtime/mysql:/var/lib/mysql
    ports:
        - "${MYSQL_PORT}:3306"
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: database
        MYSQL_USER: user
        MYSQL_PASSWORD: secret